### ISSUE TITLE
Gnome-shell crash on auto background change

### ISSUE THREAD

**Issue by jondale** [Elinvention/gnome-shell-extension-nasa-apod#13] opened 2017-10-26 13:09 UTC
When this program grabs a new image and then tries to update the background it crashes gnome-shell back to the login screen.  I see the notification come up with the description of the new image, the shell becomes unresponsive, and ~5 seconds later it crashes.  It happens every single time and it's the only crash I have.

It does grab the new image successfully and puts it in the Download folder chosen.  When I log back in the background is changed.  

I can go to the Cache tab of the extension properties and change manually.  It pops a notification saying "Network error" but it does not crash and it does change the background successfully.

I am on Fedora 26 on version 12 of the extension.  
dmesg does show the following error:
gnome-shell[2823]: segfault at 18 ip 00007f78d6e08e40 sp 00007ffeca6c3818 error 4 in libglib-2.0.so.0.5200.3[7f78d6d95000+110000]

**Comment by Elinvention** [comment] 2017-10-26 16:12
The reason for the Network error is probably because we overcome the rate limit of the default API key, and this will be indicated more clearly to the user with next version.

The reason for gnome-shell crash is... I have no idea. Perhaps I can find some hints in the output of `journalctl /usr/bin/gnome-shell`.

Thanks.

**Comment by neffo** [comment] 2018-01-12 09:53
@Elinvention I've had a few people having seeing shell crashes with my extension, it seems like gnome was trying to init() the extension more than once. I couldn't reproduce it, but saw a similar issue with a different extension (impatience).

**Comment by Elinvention** [comment] 2018-01-14 09:03
Interesting, yesterday I had this problem more than once. The problem is: how do we know that it's our extension causing the crash? And, more importantly, how do we debug this problem?

**Comment by neffo** [comment] 2018-01-14 09:22
I noticed it with impatience as the extension creates a journal entry when it is enabled (and it was being enabled twice less than a second apart). I checked to see if init() was being called twice and it was. That matched the logs issue being reported, but in the case of impatience there's nothing that would cause a crash if it ran twice.

One guy fixed it by uninstalling the extension and reinstalling it, which says to me it might be a race condition or something else related to timing or sequence. It's wierd...

**Comment by neffo** [comment] 2018-03-23 11:17
I enabled core dumps and was able to see this:
```Core was generated by `/usr/bin/gnome-shell'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  g_type_check_instance_cast (type_instance=0x55a4d98f0350, iface_type=94166481311696) at ../../../../gobject/gtype.c:4057
4057	../../../../gobject/gtype.c: No such file or directory.
[Current thread is 1 (Thread 0x7f5f7244dac0 (LWP 3864))]
(gdb) bt
#0  0x00007f5f71899de2 in g_type_check_instance_cast (type_instance=0x55a4d98f0350, iface_type=94166481311696) at ../../../../gobject/gtype.c:4057
#1  0x00007f5f6f005768 in st_label_set_text () at /usr/lib/gnome-shell/libst-1.0.so
#2  0x00007f5f6b4f6e18 in ffi_call_unix64 () at ../src/x86/unix64.S:76
#3  0x00007f5f6b4f687a in ffi_call (cif=cif@entry=0x55a4d9448f18, fn=<optimised out>, rvalue=<optimised out>, rvalue@entry=0x7ffc16949f58, avalue=avalue@entry=0x7ffc16949e50) at ../src/x86/ffi64.c:525
#4  0x00007f5f7055b3c8 in gjs_invoke_c_function(JSContext*, Function*, JS::HandleObject, JS::HandleValueArray const&, mozilla::Maybe<JS::MutableHandle<JS::Value> >, GIArgument*) (context=context@entry=0x55a4d7d8f800, function=function@entry=0x55a4d9448f00, obj=..., 
    obj@entry=..., args=..., js_rval=..., r_value=r_value@entry=0x0) at gi/function.cpp:1033
#5  0x00007f5f7055cca4 in function_call(JSContext*, unsigned int, JS::Value*) (context=0x55a4d7d8f800, js_argc=1, vp=0x55a4d7f90a28) at gi/function.cpp:1351
#6  0x00007f5f684eae6c in  () at /usr/lib/x86_64-linux-gnu/libmozjs-52.so.0
#7  0x00007f5f684ddeca in  () at /usr/lib/x86_64-linux-gnu/libmozjs-52.so.0
#8  0x00007f5f684ea6d6 in  () at /usr/lib/x86_64-linux-gnu/libmozjs-52.so.0
#9  0x00007f5f684eacaf in  () at /usr/lib/x86_64-linux-gnu/libmozjs-52.so.0
#10 0x00007f5f684eaf89 in  () at /usr/lib/x86_64-linux-gnu/libmozjs-52.so.0
#11 0x00007f5f682ded09 in  () at /usr/lib/x86_64-linux-gnu/libmozjs-52.so.0
#12 0x000028034d3c43c6 in  ()
#13 0x00007ffc1694b2e0 in  ()
#14 0x00007ffc1694ac40 in  ()
#15 0xfff9000000000000 in  ()
#16 0x00007f5f695cc360 in  () at /usr/lib/x86_64-linux-gnu/libmozjs-52.so.0
#17 0x00007f5f442739a0 in  ()
#18 0x000028034d4b6ce5 in  ()
#19 0x0000000000006820 in  ()
#20 0x00007f5eca86eec0 in  ()
#21 0x0000000000000000 in  ()
```
Makes sense that st_label_set_text () is called during the creation of the notification, but I don't understand what's causing the crash.

**Comment by equake** [comment] 2018-04-25 12:05
Love this extension. Was using Ubuntu 17.10 and was having issues. Replaced my computer, now have Ubuntu 18.04 and I'm having exactly the same issue. Just after NASA APOD extension runs, gnome hangs for 5 seconds and them crashes.

**Comment by hmaarrfk** [comment] 2018-06-24 16:21
Man, this is really sad that it is a gnome bug. I have to disable this extension while Gnome fixes their code.

Do you mind maybe pushing an update that disables notifications?

**Comment by nclarkjudd** [comment] 2018-07-22 12:50
I am having this issue. I will try disabling notifications as suggested in this thread and see if it helps. This extension is great!

**Comment by Elinvention** [comment] 2020-01-27 21:43
I don't think this happens anymore on newer GNOME versions.

**Closed by Elinvention** 2020-01-27 21:43 UTC
Labels: upstream bug
