### ISSUE TITLE
Disable indicator menu icon

### ISSUE THREAD

**Issue by hackel** [Elinvention/gnome-shell-extension-nasa-apod#4] opened 2017-05-30 16:52 UTC
Please add an option to disable the indicator menu icon.  I personally do not find it useful, and with so many other great extensions around lately, my status bar is really getting cluttered.  Thanks for the great extension!

**Comment by hackel** [comment] 2017-06-22 16:24
Thanks for implementing this!  I just got around to testing it, and the new setting is not working for me.  I've tried enabling/disabling the extension, resetting the preferences, etc.  The indicator is always shown.

**Comment by Elinvention** [comment] 2017-06-22 23:13
Please, tell me if there are some relevant errors in the output of `journalctl -f -o cat /usr/bin/gnome-shell`.

**Comment by neffo** [comment] 2017-07-28 09:18
This issue should be fixed by my pull request here #7

**Comment by Elinvention** [comment] 2017-07-28 23:17
Oh I didn't test the permanency of the setting. I submitted version 8 on extensions.gnome.org, please tell me if the issue is fixed for you when you have time to test it.

**Closed** 2017-08-30 00:27 UTC
