### ISSUE TITLE
Can't add API tokens

### ISSUE THREAD

**Issue by benjaminbhollon** [Elinvention/gnome-shell-extension-nasa-apod#44] opened 2021-11-19 07:10 UTC
**Describe the bug**

When I try to add an API token of my own, the dialog appears visually broken (check the screenshot)

**To Reproduce**

1. Go to the "Network" tab in the extension preferences (extension icon => Settings => Network)
2. Under "API keys" click "Add"

**Expected behavior**

A dialog letting me add my own API token. I'm not sure what it's supposed to look like since I only just started using this extension.

**Screenshots**

![image](https://user-images.githubusercontent.com/33023252/142579901-c07fe81a-a85a-4f1f-a012-476b4bdd7b4a.png)

**Operating system with version**
Fedora 35 (Workstation)

**GNOME Shell version**

41.1

**Installation method**
https://extensions.gnome.org/extension/1202/nasa-apod/

**Logs <- VERY IMPORTANT**

Please paste below the relevant parts of `journalctl -f -o cat /usr/bin/gnome-shell`.
If you don't use systemd, you have to find where the logs are stored and paste them here.

```
Failed to set the markup of the actor '<unnamed>[<ClutterText>:0x5556e9700290]': Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;
Timelines with detached actors are not supported
```
That's repeated, probably because I've tested this multiple times.

**Extension's settings**

Some errors might be triggered by a spefic set of settings. The command below outputs all of the extension settigs that were changed from the default value.

If you installed the extension system-wide (e.g. from AUR or distro packages) the command is:  
`gsettings --schemadir /usr/share/gnome-shell/extensions/nasa_apod@elinvention.ovh/schemas/schemas/ list-recursively org.gnome.shell.extensions.nasa-apod`.

Otherwise it is:  
`gsettings --schemadir ~/.local/share/gnome-shell/extensions/nasa_apod@elinvention.ovh/schemas/ list-recursively org.gnome.shell.extensions.nasa-apod`.

```
org.gnome.shell.extensions.nasa-apod background-options 'default'
org.gnome.shell.extensions.nasa-apod image-resolution 'hd'
org.gnome.shell.extensions.nasa-apod pinned-background ''
org.gnome.shell.extensions.nasa-apod screensaver-options 'default'
org.gnome.shell.extensions.nasa-apod image-resolution-metered 'lowres'
org.gnome.shell.extensions.nasa-apod refresh-metered false
org.gnome.shell.extensions.nasa-apod notify true
org.gnome.shell.extensions.nasa-apod hide false
org.gnome.shell.extensions.nasa-apod set-background true
org.gnome.shell.extensions.nasa-apod download-folder ''
org.gnome.shell.extensions.nasa-apod last-refresh uint64 1637304432395
org.gnome.shell.extensions.nasa-apod api-keys ['XKSoS8Bv05ij8JH8UWa7eqMavXgGfFStcc6Pu3KH', 'jCUjMOBpL523SxLoi4PogFZ3YsvvFtVNyEvRd0IB']
org.gnome.shell.extensions.nasa-apod last-json "{\"copyright\":\"Wido Oerlemans\",\"date\":\"2021-11-19\",\"explanation\":\"In visible light the stars have been removed from this narrow-band image of NGC 281, a star forming region some 10,000 light-years away toward the constellation Cassiopeia. Stars were digitally added back to the resulting starless image though. But instead of using visible light image data, the stars were added with X-ray data (in purple) from the Chandra X-ray Observatory and infrared data (in red) from the Spitzer Space Telescope. The merged multiwavelength view reveals a multitude of stars in the region's embedded star cluster IC 1590. The young stars are normally hidden in visible light images by the natal cloud's gas and obscuring dust. Also known to backyard astro-imagers as the Pacman Nebula for its overall appearance in visible light, NGC 281 is about 80 light-years across.\",\"hdurl\":\"https://apod.nasa.gov/apod/image/2111/starless_color.jpg\",\"media_type\":\"image\",\"service_version\":\"v1\",\"title\":\"NGC 281: Starless with Stars\",\"url\":\"https://apod.nasa.gov/apod/image/2111/starless_color_1024.jpg\"}\n"
org.gnome.shell.extensions.nasa-apod transient true
org.gnome.shell.extensions.nasa-apod set-lock-screen true
```

**Comment by hparlak** [comment] 2021-11-25 08:42
> **Describe the bug**
> 
> When I try to add an API token of my own, the dialog appears visually broken (check the screenshot)
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
>     1. Go to the "Network" tab in the extension preferences (extension icon => Settings => Network)
> 
>     2. Under "API keys" click "Add"
> 
> 
> **Expected behavior**
> 
> A dialog letting me add my own API token. I'm not sure what it's supposed to look like since I only just started using this extension.
> 
> **Screenshots**
> 
> ![image](https://user-images.githubusercontent.com/33023252/142579901-c07fe81a-a85a-4f1f-a012-476b4bdd7b4a.png)
> 
> **Operating system with version** Fedora 35 (Workstation)
> 
> **GNOME Shell version**
> 
> 41.1
> 
> **Installation method** https://extensions.gnome.org/extension/1202/nasa-apod/
> 
> **Logs <- VERY IMPORTANT**
> 
> Please paste below the relevant parts of `journalctl -f -o cat /usr/bin/gnome-shell`. If you don't use systemd, you have to find where the logs are stored and paste them here.
> 
> ```
> Failed to set the markup of the actor '<unnamed>[<ClutterText>:0x5556e9700290]': Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;
> Timelines with detached actors are not supported
> ```
> 
> That's repeated, probably because I've tested this multiple times.
> 
> **Extension's settings**
> 
> Some errors might be triggered by a spefic set of settings. The command below outputs all of the extension settigs that were changed from the default value.
> 
> If you installed the extension system-wide (e.g. from AUR or distro packages) the command is: `gsettings --schemadir /usr/share/gnome-shell/extensions/nasa_apod@elinvention.ovh/schemas/schemas/ list-recursively org.gnome.shell.extensions.nasa-apod`.
> 
> Otherwise it is: `gsettings --schemadir ~/.local/share/gnome-shell/extensions/nasa_apod@elinvention.ovh/schemas/ list-recursively org.gnome.shell.extensions.nasa-apod`.
> 
> ```
> org.gnome.shell.extensions.nasa-apod background-options 'default'
> org.gnome.shell.extensions.nasa-apod image-resolution 'hd'
> org.gnome.shell.extensions.nasa-apod pinned-background ''
> org.gnome.shell.extensions.nasa-apod screensaver-options 'default'
> org.gnome.shell.extensions.nasa-apod image-resolution-metered 'lowres'
> org.gnome.shell.extensions.nasa-apod refresh-metered false
> org.gnome.shell.extensions.nasa-apod notify true
> org.gnome.shell.extensions.nasa-apod hide false
> org.gnome.shell.extensions.nasa-apod set-background true
> org.gnome.shell.extensions.nasa-apod download-folder ''
> org.gnome.shell.extensions.nasa-apod last-refresh uint64 1637304432395
> org.gnome.shell.extensions.nasa-apod api-keys ['XKSoS8Bv05ij8JH8UWa7eqMavXgGfFStcc6Pu3KH', 'jCUjMOBpL523SxLoi4PogFZ3YsvvFtVNyEvRd0IB']
> org.gnome.shell.extensions.nasa-apod last-json "{\"copyright\":\"Wido Oerlemans\",\"date\":\"2021-11-19\",\"explanation\":\"In visible light the stars have been removed from this narrow-band image of NGC 281, a star forming region some 10,000 light-years away toward the constellation Cassiopeia. Stars were digitally added back to the resulting starless image though. But instead of using visible light image data, the stars were added with X-ray data (in purple) from the Chandra X-ray Observatory and infrared data (in red) from the Spitzer Space Telescope. The merged multiwavelength view reveals a multitude of stars in the region's embedded star cluster IC 1590. The young stars are normally hidden in visible light images by the natal cloud's gas and obscuring dust. Also known to backyard astro-imagers as the Pacman Nebula for its overall appearance in visible light, NGC 281 is about 80 light-years across.\",\"hdurl\":\"https://apod.nasa.gov/apod/image/2111/starless_color.jpg\",\"media_type\":\"image\",\"service_version\":\"v1\",\"title\":\"NGC 281: Starless with Stars\",\"url\":\"https://apod.nasa.gov/apod/image/2111/starless_color_1024.jpg\"}\n"
> org.gnome.shell.extensions.nasa-apod transient true
> org.gnome.shell.extensions.nasa-apod set-lock-screen true
> ```

I have the exact same issue. Same configuration, same environment, same issue.

**Comment by Elinvention** [comment] 2021-11-25 18:32
Thanks for reporting and diligently filling out all of the requested informations. This actually a duplicate of #43 and it's already fixed on main branch. I just have to make a new release and upload to extensions.gnome.org.

**Closed by Elinvention** 2021-11-25 18:32 UTC
